### ISSUE TITLE
Ctrl-P should ignore files that have no place in a text editor

### ISSUE THREAD

**Issue by xoebus** [vito/dot-nvim#1]
`$GOPATH/{pkg,bin}/*`

http://vimdoc.sourceforge.net/htmldoc/options.html#'wildignore'

**Comment by vito** [comment]
ended up doing enough to ignore `pkg/` at least on linux. might need to make further changes for os x (i think it has `.so` files and not `.a`).

i don't want to ignore `bin/` wholesale because sometimes scripts live in there that are worth editing.
